name: Check for new signature edits
on:
  schedule:
    - cron: "*/5 * * * *"
  
  workflow_dispatch:

jobs:
  check:
    name: Check for new signature changes
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14.x
        
      - name: Install Dependencies
        run: cd src && npm i
        
      - name: Check for new description changes
        run: node src/index.js
        
      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update signatures
