name: Check for new signature edits
on:
  schedule:
    - cron: "*/5 * * * *"
  
  workflow_dispatch:

jobs:
  check:
    name: Check for new signature changes
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Generate App Token
        id: generate_token
        uses: tibdex/github-app-token@v1.0.2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ steps.generate_token.outputs.token }}
        
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14.x
      
      - name: Install Dependencies
        run: cd src && npm i
        
      - name: Check for new description changes
        run: node src/index.js
          
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ steps.generate_token.outputs.token }}
          publish_dir: .
          user_name: autotable[bot]
          user_email: autotable[bot]@users.noreply.github.com
          full_commit_message: Update signatures
